### ISSUE TITLE
Dependency Inversion Principle violation from filthy code, losing sleep thinking about it

### ISSUE THREAD

**Issue by bill-c-martin** [yamut/string-reverse#1]
src/Constants.php is tightly coupled with src/Solutions/StringReverseStringSolution.php through:

```php
public function checkSupportedAlgorithms(): void {
   $this->algorithm = Constants::ALGORITHM;
}
```

Code violates Dependency Inversion Principle, therefore not SOLID enough, and is therefore immoral. Recommend architecting it properly using Strategy Pattern to inject an interface in the signature passing an object implementation containing the Constants::ALGORITHM.

**Comment by bill-c-martin** [comment]
@yamut, I will submit a PR tonight to correct this gross insult.

**Comment by bill-c-martin** [comment]
@stretchnate we may need your assistance with this meta-ethical quandary.

**Comment by yamut** [comment]
@bill-c-martin Please accept my apologies for this disgusting mess.

**Comment by stretchnate** [comment]
@bill-c-martin not to be a code snob but checkSupportedAlgorithms also sounds like an accessor but acts like a manipulator... sort of, I guess it always sets the same value to $this->algorithm (at least until you refactor it). Still, I'd consider renaming it to something like loadSupportedAlgorithms but that's just me and my OCD.

**Comment by bill-c-martin** [comment]
Good point, it is criminal that a "checking" method behaves like a setter, and doesn't even return a boolean. Entire codebase may need to be discarded now.

**Comment by bill-c-martin** [comment]
@stretchnate, we need to review the code under /src and over-architect it some more so that it is enterprise-compliant. Needs more interfaces, abstractions, design patterns, anything complicated that we can throw at it so we hit the ground running when we deploy it to prod.

**Comment by yamut** [comment]
@stretchnate @bill-c-martin You're right, I will file a separate issue regarding my amateur showing.

**Comment by yamut** [comment]
#2

**Comment by stretchnate** [comment]
where are you deploying this and who for?

**Comment by bill-c-martin** [comment]
This is for enterprise companies who need an overly complex enterprise solution for string reversal in php. Because `strrev()` is too simple and not enterprise enough.

**Comment by yamut** [comment]
85a222fdfbf1652c234860163c240897712c29e8

I just confused myself.

**Comment by stretchnate** [comment]
Makes perfect sense, how can I cause a problem?

**Comment by bill-c-martin** [comment]
@stretchnate must optimize code to be as enterprise as possible, whilst justifying nitpicking by referencing any and all programming and architectural theory. Buzzwords are a must! Bonus points for also using the [Corporate B.S. Generator](http://www.atrixnet.com/bs-generator.html) on why a change needs to be made.

**Comment by yamut** [comment]
On that note, blockchain.

I look forward to seeing all of your money wired posthaste.
