### ISSUE TITLE
checkSupportedAlgorithms sounds like an accessor but acts like a manipulator

### ISSUE THREAD

**Issue by yamut** [yamut/string-reverse#2]
Refactor this method to follow less disgusting principles.

**Comment by yamut** [comment]
I don't know what the fuck I just did.

**Comment by yamut** [comment]
85a222fdfbf1652c234860163c240897712c29e8

**Comment by bill-c-martin** [comment]
If you don't know what you just did, then nobody else will. That makes it exclusive. Which means you can charge exorbitant subscription fees. Which reinforces that this is indeed an enterprise-grade package. Why use open source freeware `strrev()`, when you can pay for this instead and hire a string-reverse consultant?
