### ISSUE TITLE
Add content to readme

### ISSUE THREAD

**Issue by yamut** [yamut/string-reverse#5]
Readme is far too concise for enterprise software, need to add additional fluff and garbage.

**Comment by bill-c-martin** [comment]
#6 has a couple quotes in the readme, that IBM gave us at IBM Think 2018, and that Packagist.org tweeted the other day about us. Our bricks-and-clicks relationships are creating a lot of market synergy.

**Comment by yamut** [comment]
Issue resolved under #6
