### ISSUE TITLE
Create performance test

### ISSUE THREAD

**Issue by yamut** [yamut/string-reverse#9]
How can this be enterprise if it has not been sufficiently tested to handle both large volume and large strings?

Add this functionality.

**Comment by yamut** [comment]
Got an interesting fatal error while testing the test

```
............BEGIN testLengthPerformance

PHP Fatal error:  Allowed
```

**Comment by yamut** [comment]
#10

**Comment by bill-c-martin** [comment]
+1 for doing the needful.
